### ISSUE TITLE
require glue will get error 

### ISSUE THREAD

**Issue by ChrisCatCP** [allegory-software/allegory-sdk#6]
branch: dev
```
glue.lua:1728: variable 'Error' is not declared
```
this is my patch ,I don't know if this is correct

```
glue.lua
@@ -1838,7 +1838,7 @@ _G.protect = protect

 --base error class that all error types inherit from.

-Error = errortype()
+Error = {}
```

**Comment by capr** [comment]
If you use strict.lua you're in for a lot of fixin'... I read globals that might not be defined in a few places.

**Comment by ChrisCatCP** [comment]
okay, i ll take care of it

**Comment by capr** [comment]
Ok, closing, feel free to reopen if there's more I can help you with. If strict.lua is important to you I might consider fixing those places where undefined globals are accessed... so far I didn't need it.
